name: 'Demo Deployments'

on:
  - push
  - release:
    types: ['published']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Setup pnpm
        run: npm install pnpm -g

      - name: Install
        run: pnpm install

      - name: Build object-fit demo
        run: pnpm run build:object-fit-demo:with_dependencies

      - name: Deploy object-fit demo
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=packages/library/css/object-fit/demo/public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.OBJECT_FIT_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Production deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true